### ISSUE TITLE
Bug: Hit button repeatedly

### ISSUE THREAD

**Issue by kichikuchi** [nakajijapan/Shari#15]
I found bug when I hit button repeatedly.

![shari_bug](https://cloud.githubusercontent.com/assets/3441454/20171199/e81f055a-a772-11e6-83ee-518d6faba9b3.gif)

**Comment by nakajijapan** [comment]
Hi, @kichikuchi 

I fixed in #16, please check!!

**Comment by nakajijapan** [comment]
Released!
https://github.com/nakajijapan/Shari/releases/tag/0.5.1

**Comment by kichikuchi** [comment]
azaaaasu
